type RACONAS =
  | "Computer Science"
  | "BIOCHEMISTRY"
  | "MICROBIOLOGY"
  | "CHEMISTRY"
  | "INDUSTRIAL CHEMISTRY"
  | "PHYSICS & ELECTRONICS";

type CMSS =
  | "ACCOUNTING"
  | "BANKING & FINANCE"
  | "ECONOMICS"
  | "BUSINESS ADMINISTRATION"
  | "INTERNATIONAL RELATIONS"
  | "POLITICAL SCIENCE";

type RACOET =
  | "COMPUTER ENGINEERING"
  | "MECHANICAL ENGINEERING"
  | "ELECTRICAL & ELECTRONICS ENGINEERING";

type OOSCEDM = "ARCHITECTURE" | "ESTATE MANAGEMENT" | "QUANTITY SURVEYING";

type COCAMS = "MASS COMMUNICATION";

type NURSING = "NURSING SCIENCE";

type LAW = "LAW";

type Faculty =
  | "None"
  | "RACONAS"
  | "NURSING"
  | "LAW"
  | "CMSS"
  | "RACOET"
  | "COCAMS"
  | "OOSCEDM";

interface FacultyDepartment {
  RACONAS: RACONAS[];
  NURSING: NURSING[];
  LAW: LAW[];
  CMSS: CMSS[];
  RACOET: RACOET[];
  COCAMMS: COCAMS[];
  OOSCEDM: OOSCEDM[];
}

export const Department: FacultyDepartment = {
  RACONAS: [
    "Computer Science",
    "BIOCHEMISTRY",
    "MICROBIOLOGY",
    "CHEMISTRY",
    "INDUSTRIAL CHEMISTRY",
    "PHYSICS & ELECTRONICS",
  ],
  NURSING: ["NURSING SCIENCE"],
  LAW: ["LAW"],
  CMSS: [
    "ACCOUNTING",
    "BANKING & FINANCE",
    "ECONOMICS",
    "BUSINESS ADMINISTRATION",
    "INTERNATIONAL RELATIONS",
    "POLITICAL SCIENCE",
  ],
  RACOET: [
    "COMPUTER ENGINEERING",
    "MECHANICAL ENGINEERING",
    "ELECTRICAL & ELECTRONICS ENGINEERING",
  ],
  COCAMMS: ["MASS COMMUNICATION"],
  OOSCEDM: ["ARCHITECTURE", "ESTATE MANAGEMENT", "QUANTITY SURVEYING"],
};

console.log(Department);
