# Generated by Django 5.0.6 on 2024-06-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0002_alter_balance_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000000000, max_digits=100),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='fees',
            field=models.ManyToManyField(to='voucher.fee'),
        ),
    ]
