# Generated by Django 5.0.6 on 2024-06-13 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0003_alter_balance_balance_alter_voucher_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
