# Generated by Django 5.0.6 on 2024-07-23 07:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0004_voucher_timestamp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRefrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255, unique=True)),
                ('matric_number', models.CharField(max_length=225)),
                ('email_number', models.EmailField(max_length=225)),
                ('success', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('domain', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('receipt_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField()),
                ('message', models.TextField(blank=True, null=True)),
                ('gateway_response', models.CharField(max_length=255)),
                ('paid_at', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('channel', models.CharField(max_length=50)),
                ('currency', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('fees', models.IntegerField()),
                ('authorization_code', models.CharField(max_length=255)),
                ('card_bin', models.CharField(max_length=50)),
                ('last4', models.CharField(max_length=4)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=4)),
                ('card_type', models.CharField(max_length=50)),
                ('bank', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=2)),
                ('brand', models.CharField(max_length=50)),
                ('reusable', models.BooleanField()),
                ('signature', models.CharField(max_length=255)),
                ('customer_id', models.BigIntegerField()),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_code', models.CharField(max_length=255)),
                ('customer_phone', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField()),
                ('log', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
