# Generated by Django 5.0.6 on 2024-07-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0008_alter_payment_payment_sessionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='vouchr_used',
            field=models.BooleanField(default=False),
        ),
    ]
