# Generated by Django 5.0.6 on 2024-07-25 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0010_rename_vouchr_used_payment_voucher_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voucher',
            old_name='voucher_name',
            new_name='session_id',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='created_for',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='encrypt_voucher',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='password',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='start_date',
        ),
    ]
