# Generated by Django 5.0.6 on 2024-07-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0011_rename_voucher_name_voucher_session_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('serial', models.CharField(max_length=24, unique=True)),
                ('serial_number', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('date_used', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
