# Generated by Django 5.0.6 on 2024-07-26 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voucher', '0012_vouchertoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchertoken',
            name='token',
            field=models.CharField(default=1, max_length=225),
            preserve_default=False,
        ),
    ]
