# Generated by Django 5.0.6 on 2024-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_matric_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Mal', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
